import localFont from "next/font/local";
import "./globals.css";
import { Container } from "@mui/material";
import Contacts from "./components/headers/Contacts";
import NavBar from "./components/headers/NavBar";
import { Cairo } from "next/font/google";


const cairo = Cairo({
	subsets: ['arabic'],
	display: 'swap',
	variable: "--font-cairo"
})

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl" className={cairo.className}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${cairo.variable}  antialiased h-screen`}
      >
        <Contacts />
        <NavBar />
        {children}
      </body>
    </html>
  );
}
